# Generated by Django 5.1.7 on 2025-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='auction',
            field=models.BooleanField(default=False),
        ),
    ]
