# Generated by Django 5.1.7 on 2025-03-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artist_can_post_painting_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='canvas_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='painting',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='paint_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='year_of_creation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
