# Generated by Django 5.1.7 on 2025-03-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_painting_canvas_material_painting_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='photos/no_image.jpg', upload_to='photos/'),
        ),
    ]
