# Generated by Django 5.1.7 on 2025-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_painting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
