# Generated by Django 5.1.7 on 2025-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default='photos/no_image.jpg', upload_to='profile_pics/'),
        ),
    ]
